<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="ALTA_empleado_Service"
     targetNamespace="http://oracle.com/sca/soapservice/ApplicationOSB/GestionEmpleadoProject/ALTA_empleado_Service"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:inp1="http://www.everis.com/empleado"
     xmlns:tns="http://oracle.com/sca/soapservice/ApplicationOSB/GestionEmpleadoProject/ALTA_empleado_Service"
    >
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.everis.com/empleado" schemaLocation="xsd/empleado.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="part1" element="inp1:empleado"/>
    </wsdl:message>
    <wsdl:portType name="alta_ptt">
        <wsdl:operation name="alta">
            <wsdl:input message="tns:requestMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
