<?binding.jca UPDATE_empleado_db.jca?>
<wsdl:definitions name="UPDATE_empleado" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ApplicationOSB/GestionEmpleadoProject/UPDATE_empleado" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ApplicationOSB/GestionEmpleadoProject/UPDATE_empleado" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/UPDATE_empleado">
    <plt:partnerLinkType name="UPDATE_empleado_plt">
        <plt:role name="UPDATE_empleado_role">
            <plt:portType name="tns:UPDATE_empleado_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/UPDATE_empleado" schemaLocation="xsd/UPDATE_empleado_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="EmpleadosCollection_msg">
        <wsdl:part name="EmpleadosCollection" element="top:EmpleadosCollection"/>
    </wsdl:message>
    <wsdl:portType name="UPDATE_empleado_ptt">
        <wsdl:operation name="update">
            <wsdl:input message="tns:EmpleadosCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
